export const configuration = {
  title: process.env.genTitle ?? '',
  titleSuperscript: process.env.genTitleSuperscript ?? '',
  name: process.env.genName ?? '',
  description: process.env.genDescription ?? '',
  gitHubUrl: process.env.genGitHubUrl ?? '',
  author: process.env.genAuthor ?? '',
  SEOTags: process.env.genSEOTags ?? '',
  rootPath: process.env.genRootPath ?? '/',
  readmeFileName: process.env.genreadmeFileName ?? 'README.md',
  codeDocs: process.env.genCodeDocs !== 'none',
  codeDocsPath: process.env.genCodeDocsPath ?? '',
  markdownPages: process.env.genMarkdownPages !== 'none',
  markdownPagesPath: process.env.genMarkdownPagesPath ?? '',
  themeImageLogo: process.env.genThemeImageLogo ?? '',
}
